name: Deploy to Server

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Post-deployment tasks
      run: |
        echo ${{ secrets.SERVER_HOST:0:4 }}
